services:
  postgres:
    image: postgres
    container_name: catalogodosabio-postgres
    environment:
      POSTGRES_USER: catalogodosabioadmin
      POSTGRES_PASSWORD: topsecret123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U catalogodosabioadmin" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis
    container_name: catalogodosabio-redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: catalogodosabio-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_HOST: postgres
      SPRING_REDIS_HOST: redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  pgdata: